[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
